"commit_message": "[ci skip]"
"files": [
  {
    "source" : "/content/en/*",                                               #source files filter
    "translation" : "/content/%locale_with_underscore%/%original_file_name%"  #where translations are stored
  }
]
